name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'  

      - name: Install dependencies
        working-directory: flutter_solid_notifications
        run: flutter pub get

      - name: Run tests
        working-directory: flutter_solid_notifications
        run: flutter test

      - name: Build APK
        working-directory: flutter_solid_notifications
        run: flutter build apk --release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-build
          path: flutter_solid_notifications/build/app/outputs/flutter-apk/app-release.apk
